/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BeatSerializer } from './BeatSerializer';
import {
    BeatSerializerFromJSON,
    BeatSerializerFromJSONTyped,
    BeatSerializerToJSON,
} from './BeatSerializer';

/**
 * Identifies the beat in which this event becomes available.
 * @export
 * @interface AvailableBeat
 */
export interface AvailableBeat {
    /**
     * ID of the beat.
     * @type {string}
     * @memberof AvailableBeat
     */
    id?: string;
    /**
     * Name of the beat.
     * @type {string}
     * @memberof AvailableBeat
     */
    name?: string;
}

/**
 * Check if a given object implements the AvailableBeat interface.
 */
export function instanceOfAvailableBeat(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AvailableBeatFromJSON(json: any): AvailableBeat {
    return AvailableBeatFromJSONTyped(json, false);
}

export function AvailableBeatFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableBeat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function AvailableBeatToJSON(value?: AvailableBeat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

