/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents a beat object on a narrative timeline.
 * @export
 * @interface BeatSerializer
 */
export interface BeatSerializer {
    /**
     * ID of the beat.
     * @type {string}
     * @memberof BeatSerializer
     */
    id?: string;
    /**
     * Name of the beat.
     * @type {string}
     * @memberof BeatSerializer
     */
    name?: string;
}

/**
 * Check if a given object implements the BeatSerializer interface.
 */
export function instanceOfBeatSerializer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BeatSerializerFromJSON(json: any): BeatSerializer {
    return BeatSerializerFromJSONTyped(json, false);
}

export function BeatSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeatSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BeatSerializerToJSON(value?: BeatSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

