/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents content referenced in an external data source to an event state.
 * @export
 * @interface ContentIntegrationSerializer
 */
export interface ContentIntegrationSerializer {
    /**
     * 
     * @type {string}
     * @memberof ContentIntegrationSerializer
     */
    contentId: string;
    /**
     * 
     * @type {string}
     * @memberof ContentIntegrationSerializer
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof ContentIntegrationSerializer
     */
    providerId: string;
}

export function ContentIntegrationSerializerFromJSON(json: any): ContentIntegrationSerializer {
    return ContentIntegrationSerializerFromJSONTyped(json, false);
}

export function ContentIntegrationSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentIntegrationSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentId': json['content_id'],
        'contentType': json['content_type'],
        'providerId': json['provider_id'],
    };
}

export function ContentIntegrationSerializerToJSON(value?: ContentIntegrationSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content_id': value.contentId,
        'content_type': value.contentType,
        'provider_id': value.providerId,
    };
}

