/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Used when creating a new user entity.
 * 
 * The timeline ID and timezone is explicitly provided by the client - while the user
 * email address and other mandatory fields are extracted from the verified JWT token
 * sent in the authorization header.
 * @export
 * @interface CreateUserDeserializer
 */
export interface CreateUserDeserializer {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDeserializer
     */
    publishedTimelineId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDeserializer
     */
    timezone: string;
    /**
     * Feature flag to bypass time based guards per user.
     * @type {boolean}
     * @memberof CreateUserDeserializer
     */
    disableTimeGuards?: boolean;
    /**
     * Feature flag to toggle pausing execution of progression at beat markers.
     * @type {boolean}
     * @memberof CreateUserDeserializer
     */
    pauseAtBeats?: boolean;
}

export function CreateUserDeserializerFromJSON(json: any): CreateUserDeserializer {
    return CreateUserDeserializerFromJSONTyped(json, false);
}

export function CreateUserDeserializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDeserializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publishedTimelineId': json['published_timeline_id'],
        'timezone': json['timezone'],
        'disableTimeGuards': !exists(json, 'disable_time_guards') ? undefined : json['disable_time_guards'],
        'pauseAtBeats': !exists(json, 'pause_at_beats') ? undefined : json['pause_at_beats'],
    };
}

export function CreateUserDeserializerToJSON(value?: CreateUserDeserializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'published_timeline_id': value.publishedTimelineId,
        'timezone': value.timezone,
        'disable_time_guards': value.disableTimeGuards,
        'pause_at_beats': value.pauseAtBeats,
    };
}

