/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserInvokedTimelineEventState } from './UserInvokedTimelineEventState';
import {
    UserInvokedTimelineEventStateFromJSON,
    UserInvokedTimelineEventStateFromJSONTyped,
    UserInvokedTimelineEventStateToJSON,
} from './UserInvokedTimelineEventState';

/**
 * Update the `state` of a user timeline event via command.
 * @export
 * @interface PatchUserTimelineEventDeserializer
 */
export interface PatchUserTimelineEventDeserializer {
    /**
     * 
     * @type {UserInvokedTimelineEventState}
     * @memberof PatchUserTimelineEventDeserializer
     */
    state: UserInvokedTimelineEventState;
}

/**
 * Check if a given object implements the PatchUserTimelineEventDeserializer interface.
 */
export function instanceOfPatchUserTimelineEventDeserializer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "state" in value;

    return isInstance;
}

export function PatchUserTimelineEventDeserializerFromJSON(json: any): PatchUserTimelineEventDeserializer {
    return PatchUserTimelineEventDeserializerFromJSONTyped(json, false);
}

export function PatchUserTimelineEventDeserializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUserTimelineEventDeserializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': UserInvokedTimelineEventStateFromJSON(json['state']),
    };
}

export function PatchUserTimelineEventDeserializerToJSON(value?: PatchUserTimelineEventDeserializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': UserInvokedTimelineEventStateToJSON(value.state),
    };
}

