/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Deserializer used on the progress events RPC endpoint which invokes the execution
 * of the beat machine.
 * 
 * The optional `max_steps` field provides a way for the integration engineer to
 * control this execution context.
 * 
 * The optional `pause_at_beats` field provides a way to override the user level
 * `pause_at_beats` configuration.
 * @export
 * @interface ProgressEventsDeserializer
 */
export interface ProgressEventsDeserializer {
    /**
     * The maximum amount of steps that should be progressed
     * @type {number}
     * @memberof ProgressEventsDeserializer
     */
    maxSteps?: number;
    /**
     * Should beat guards be respected when progressing
     * @type {boolean}
     * @memberof ProgressEventsDeserializer
     */
    pauseAtBeats?: boolean;
}

/**
 * Check if a given object implements the ProgressEventsDeserializer interface.
 */
export function instanceOfProgressEventsDeserializer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProgressEventsDeserializerFromJSON(json: any): ProgressEventsDeserializer {
    return ProgressEventsDeserializerFromJSONTyped(json, false);
}

export function ProgressEventsDeserializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgressEventsDeserializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maxSteps': !exists(json, 'max_steps') ? undefined : json['max_steps'],
        'pauseAtBeats': !exists(json, 'pause_at_beats') ? undefined : json['pause_at_beats'],
    };
}

export function ProgressEventsDeserializerToJSON(value?: ProgressEventsDeserializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max_steps': value.maxSteps,
        'pause_at_beats': value.pauseAtBeats,
    };
}

