/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';
import type { UserTimelineEventSerializer } from './UserTimelineEventSerializer';
import {
    UserTimelineEventSerializerFromJSON,
    UserTimelineEventSerializerFromJSONTyped,
    UserTimelineEventSerializerToJSON,
} from './UserTimelineEventSerializer';

/**
 * Base serializer class for all responses.
 * @export
 * @interface ResponseSerializerUserTimelineEventSerializer
 */
export interface ResponseSerializerUserTimelineEventSerializer {
    /**
     * 
     * @type {UserTimelineEventSerializer}
     * @memberof ResponseSerializerUserTimelineEventSerializer
     */
    data?: UserTimelineEventSerializer;
    /**
     * 
     * @type {Error}
     * @memberof ResponseSerializerUserTimelineEventSerializer
     */
    error?: Error | null;
    /**
     * 
     * @type {Meta}
     * @memberof ResponseSerializerUserTimelineEventSerializer
     */
    meta?: Meta | null;
}

/**
 * Check if a given object implements the ResponseSerializerUserTimelineEventSerializer interface.
 */
export function instanceOfResponseSerializerUserTimelineEventSerializer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseSerializerUserTimelineEventSerializerFromJSON(json: any): ResponseSerializerUserTimelineEventSerializer {
    return ResponseSerializerUserTimelineEventSerializerFromJSONTyped(json, false);
}

export function ResponseSerializerUserTimelineEventSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSerializerUserTimelineEventSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UserTimelineEventSerializerFromJSON(json['data']),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
    };
}

export function ResponseSerializerUserTimelineEventSerializerToJSON(value?: ResponseSerializerUserTimelineEventSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserTimelineEventSerializerToJSON(value.data),
        'error': value.error,
        'meta': MetaToJSON(value.meta),
    };
}

