/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const ServiceStatus = {
    Online: 'ONLINE',
    Maintenance: 'MAINTENANCE'
} as const;
export type ServiceStatus = typeof ServiceStatus[keyof typeof ServiceStatus];


export function ServiceStatusFromJSON(json: any): ServiceStatus {
    return ServiceStatusFromJSONTyped(json, false);
}

export function ServiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatus {
    return json as ServiceStatus;
}

export function ServiceStatusToJSON(value?: ServiceStatus | null): any {
    return value as any;
}

