/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * API representation of timeline resource.
 * @export
 * @interface TimelineSerializer
 */
export interface TimelineSerializer {
    /**
     * 
     * @type {string}
     * @memberof TimelineSerializer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineSerializer
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineSerializer
     */
    description?: string;
}

/**
 * Check if a given object implements the TimelineSerializer interface.
 */
export function instanceOfTimelineSerializer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function TimelineSerializerFromJSON(json: any): TimelineSerializer {
    return TimelineSerializerFromJSONTyped(json, false);
}

export function TimelineSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function TimelineSerializerToJSON(value?: TimelineSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
    };
}

