/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Instead of our serializer level objects inheriting from BaseModel, they
 * should all inherit from BaseSerializer, which removes the burden of handling the
 * lookup of a entity key identifiers within our API view logic.
 * 
 * By enabling ORM_MODE we can pass in schema objects, and Pydantic will do a
 * __getattr__ style lookup, which will auto unpack the primary key from our
 * BaseSchema inherited object.
 * 
 * We also have a thin wrapper around the __init__, which helps to provide a nicer API
 * when unpacking the results of projection queries into our resource serializers. This
 * can be used in conjunction with the `get_projection_properties` helper to get all
 * entity property names from the datastore index.
 * @export
 * @interface TokenIntrospectionDeserializer
 */
export interface TokenIntrospectionDeserializer {
    /**
     * Access Token to introspect
     * @type {string}
     * @memberof TokenIntrospectionDeserializer
     */
    accessToken: string;
}

export function TokenIntrospectionDeserializerFromJSON(json: any): TokenIntrospectionDeserializer {
    return TokenIntrospectionDeserializerFromJSONTyped(json, false);
}

export function TokenIntrospectionDeserializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenIntrospectionDeserializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
    };
}

export function TokenIntrospectionDeserializerToJSON(value?: TokenIntrospectionDeserializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
    };
}

