/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Read only representation of the meta data around an access token.
 * @export
 * @interface TokenIntrospectionSerializer
 */
export interface TokenIntrospectionSerializer {
    /**
     * Status of the token.
     * @type {boolean}
     * @memberof TokenIntrospectionSerializer
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenIntrospectionSerializer
     */
    userId?: string;
    /**
     * Time in seconds until the access token expires.
     * @type {number}
     * @memberof TokenIntrospectionSerializer
     */
    expiresIn?: number;
}

export function TokenIntrospectionSerializerFromJSON(json: any): TokenIntrospectionSerializer {
    return TokenIntrospectionSerializerFromJSONTyped(json, false);
}

export function TokenIntrospectionSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenIntrospectionSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isActive': json['is_active'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'expiresIn': !exists(json, 'expires_in') ? undefined : json['expires_in'],
    };
}

export function TokenIntrospectionSerializerToJSON(value?: TokenIntrospectionSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_active': value.isActive,
        'user_id': value.userId,
        'expires_in': value.expiresIn,
    };
}

