/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * All states UserTimelineEvent entities can be in.
 * @export
 */
export const UserTimelineEventState = {
    Initial: 'INITIAL',
    Available: 'AVAILABLE',
    Started: 'STARTED',
    Completed: 'COMPLETED',
    Skipped: 'SKIPPED',
    Removed: 'REMOVED',
    Unavailable: 'UNAVAILABLE',
    Purged: 'PURGED',
    Consumed: 'CONSUMED'
} as const;
export type UserTimelineEventState = typeof UserTimelineEventState[keyof typeof UserTimelineEventState];


export function UserTimelineEventStateFromJSON(json: any): UserTimelineEventState {
    return UserTimelineEventStateFromJSONTyped(json, false);
}

export function UserTimelineEventStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTimelineEventState {
    return json as UserTimelineEventState;
}

export function UserTimelineEventStateToJSON(value?: UserTimelineEventState | null): any {
    return value as any;
}

