/* tslint:disable */
/* eslint-disable */
/**
 * Fictioneers - Audience APIs.
 * JSON APIs used to integrate with the Fictioneers platform served from https://api.fictioneers.co.uk
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * All states a User can update a UserTimelineEvent state value to over API.
 * @export
 */
export const UserInvokedTimelineEventState = {
    Available: 'AVAILABLE',
    Started: 'STARTED',
    Cancelled: 'CANCELLED',
    Completed: 'COMPLETED',
    Skipped: 'SKIPPED',
    Consumed: 'CONSUMED'
} as const;
export type UserInvokedTimelineEventState = typeof UserInvokedTimelineEventState[keyof typeof UserInvokedTimelineEventState];


export function UserInvokedTimelineEventStateFromJSON(json: any): UserInvokedTimelineEventState {
    return UserInvokedTimelineEventStateFromJSONTyped(json, false);
}

export function UserInvokedTimelineEventStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInvokedTimelineEventState {
    return json as UserInvokedTimelineEventState;
}

export function UserInvokedTimelineEventStateToJSON(value?: UserInvokedTimelineEventState | null): any {
    return value as any;
}

