/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/token": {
    /** Access Tokens are tied to a specific user, shorted lived (1 hour), and can only be used to authenticate with the Audience API. */
    post: operations["generate_tokens_auth_token_post"];
  };
  "/auth/introspect-token": {
    /**
     * Inspect an access token generated by the authentication API, to view
     * metadata including the expiry datetime.
     */
    post: operations["token_info_auth_introspect_token_post"];
  };
  "/v1/auth/token": {
    /** Access Tokens are tied to a specific user, shorted lived (1 hour), and can only be used to authenticate with the Audience API. */
    post: operations["generate_tokens_v1_auth_token_post"];
  };
  "/v1/auth/introspect-token": {
    /**
     * Inspect an access token generated by the authentication API, to view
     * metadata including the expiry datetime.
     */
    post: operations["token_info_v1_auth_introspect_token_post"];
  };
  "/users/me": {
    /** Retrieve detailed representation of the current user. */
    get: operations["get_user_me_users_me_get"];
    /** Delete the user and any user associated objects from the current timeline. */
    delete: operations["delete_user_users_me_delete"];
  };
  "/users": {
    /** Create a new audience user for a Fictioneers powered experience. */
    post: operations["create_user_users_post"];
  };
  "/users/me/progress-step": {
    /** Progress along the timeline. */
    post: operations["step_events_for_user_via_post_users_me_progress_step_post"];
  };
  "/user-timeline-events": {
    /** List endpoint for user timeline events. */
    get: operations["list_user_timeline_events_user_timeline_events_get"];
  };
  "/user-timeline-events/{user_timeline_event_id}/follow-link": {
    /** Update the state of the current event to COMPLETED and make the target of the link AVAILABLE (if it has also been reached by step based progression). */
    post: operations["follow_link_user_timeline_events__user_timeline_event_id__follow_link_post"];
  };
  "/user-timeline-event-state-changes": {
    /**
     * List endpoint for user timeline event state changes implicitly filtered by the
     * authenticated user ID.
     */
    get: operations["get_user_timeline_event_state_changes_user_timeline_event_state_changes_get"];
  };
  "/v1/users/me": {
    /** Retrieve detailed representation of the current user. */
    get: operations["get_user_me_v1_users_me_get"];
    /** Delete the user and any user associated objects from the current timeline. */
    delete: operations["delete_user_v1_users_me_delete"];
  };
  "/v1/users": {
    /** Create a new audience user for a Fictioneers powered experience. */
    post: operations["create_user_v1_users_post"];
  };
  "/v1/users/me/progress-step": {
    /** Progress along the timeline. */
    post: operations["step_events_for_user_via_post_v1_users_me_progress_step_post"];
  };
  "/v1/user-timeline-events": {
    /** List endpoint for user timeline events. */
    get: operations["list_user_timeline_events_v1_user_timeline_events_get"];
  };
  "/v1/user-timeline-events/{user_timeline_event_id}/follow-link": {
    /** Update the state of the current event to COMPLETED and make the target of the link AVAILABLE (if it has also been reached by step based progression). */
    post: operations["follow_link_v1_user_timeline_events__user_timeline_event_id__follow_link_post"];
  };
  "/v1/user-timeline-event-state-changes": {
    /**
     * List endpoint for user timeline event state changes implicitly filtered by the
     * authenticated user ID.
     */
    get: operations["get_user_timeline_event_state_changes_v1_user_timeline_event_state_changes_get"];
  };
  "/v1/timelines": {
    /** List all published timelines which users can be placed on. */
    get: operations["get_timelines_v1_timelines_get"];
  };
  "/v1/timelines/{timeline_id}": {
    /** Representation of a single timeline. */
    get: operations["get_timeline_v1_timelines__timeline_id__get"];
  };
  "/v1/timelines/{timeline_id}/variables": {
    /** Lists all variables with their default and current values. */
    get: operations["list_timeline_variables_v1_timelines__timeline_id__variables_get"];
  };
  "/v1/timelines/{timeline_id}/variables/{name}": {
    /** Detail representation of a single timeline variable. */
    get: operations["detail_timeline_variable_v1_timelines__timeline_id__variables__name__get"];
    /** Update the value of a shared timeline variable. */
    patch: operations["update_timeline_variable_v1_timelines__timeline_id__variables__name__patch"];
  };
  "/v1/timelines/{timeline_id}/timeline-events": {
    /** Lists all timeline events on a specific timeline. */
    get: operations["list_timeline_timeline_events_v1_timelines__timeline_id__timeline_events_get"];
  };
  "/v1/timelines/{timeline_id}/users": {
    /** List of all users on timeline. */
    get: operations["get_timeline_users_v1_timelines__timeline_id__users_get"];
    /** Delete all users on a timeline. */
    delete: operations["delete_all_timeline_users_v1_timelines__timeline_id__users_delete"];
  };
  "/v1/timelines/{timeline_id}/users/{user_id}": {
    /** Retrieves timeline user. */
    get: operations["get_timeline_user_v1_timelines__timeline_id__users__user_id__get"];
    /** Delete timeline user. */
    delete: operations["delete_timeline_user_v1_timelines__timeline_id__users__user_id__delete"];
  };
  "/v1/timelines/{timeline_id}/event-state-changes": {
    /** Returns all event state changes filtered by timeline. */
    get: operations["list_all_timeline_event_state_changes_v1_timelines__timeline_id__event_state_changes_get"];
  };
}

export interface components {
  schemas: {
    /**
     * Beat
     * @description Represents a beat object on a narrative timeline.
     */
    Beat: {
      /**
       * Id
       * @description ID of the beat.
       * @example KLJviYC7MNS7owT7ujWtb7rIHB6
       */
      id?: string;
      /**
       * Name
       * @description Name of the beat.
       * @example Act 1 Beat 3
       */
      name?: string;
    };
    /**
     * ContentIntegration
     * @description Represents content referenced in an external data source to an event state.
     */
    ContentIntegration: {
      /**
       * Content Id
       * @example MN7S90NBDJ
       */
      content_id: string;
      /**
       * Content Type
       * @example BlogPost
       */
      content_type: string;
      /**
       * Provider Id
       * @example Contentful
       */
      provider_id: string;
    };
    /**
     * CreateUserRequest
     * @description Data required when creating a new audience user.
     */
    CreateUserRequest: {
      /**
       * Published Timeline Id
       * @description Published Timeline ID which the created user should be placed on
       * @example 5UNDJoOUBDfSoMlW97a
       */
      published_timeline_id: string;
      /**
       * Timezone used for time based progression conditions
       * @example Europe/London
       */
      timezone: string;
      /**
       * Disable Time Guards
       * @description Feature flag to bypass time based guards per user.
       * @default false
       * @example false
       */
      disable_time_guards?: boolean;
      /**
       * Pause At Beats
       * @description Feature flag to toggle pausing execution of progression at beat markers.
       * @default false
       * @example false
       */
      pause_at_beats?: boolean;
      /**
       * Max Steps
       * @description The maximum amount of steps that should be progressed. Use `null` to progress until you meet a blocking condition.
       */
      max_steps?: number;
      /**
       * Variables
       * @description Override default variable values.
       * @default {}
       * @example {
       *   "credits": "100"
       * }
       */
      variables?: { [key: string]: string };
    };
    /**
     * EventStateChange
     * @description API representation of the EventStateChange resource.
     */
    EventStateChange: {
      /** Esc Type */
      esc_type: string;
      /** Narrative Event Id */
      narrative_event_id: string;
      /** Timeline Event Id */
      timeline_event_id: string;
      /** Thread Id */
      thread_id?: string;
      /** Beat Id */
      beat_id?: string;
      /** Available Step Index */
      available_step_index: number;
      /** Processed Step Index */
      processed_step_index: number;
      /** Workspace Id */
      workspace_id: string;
      /** Project Id */
      project_id: string;
      /** Timeline Id */
      timeline_id: string;
      /** User Id */
      user_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * FollowLinkRequest
     * @description Follow a link from one user timeline event to another.
     */
    FollowLinkRequest: {
      /**
       * Link Id
       * @description The link ID to follow
       * @example kNSI3QNGVj3OwByy43ze:MN7S90NBDJNSJS
       */
      link_id: string;
    };
    /**
     * GeneralError
     * @description Provides details around errors and problems encountered while performing an
     * HTTP operation.
     */
    GeneralError: {
      /** Detail */
      detail?: string;
      /** Content */
      content?: { [key: string]: unknown }[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Meta
     * @description Provides meta information related to the HTTP request.
     *
     * When progressing an audience user narrative state this includes all timeline
     * events which have been created or update, to avoid a subsequent HTTP request
     * to the API.
     */
    Meta: {
      user?: components["schemas"]["User"];
      /**
       * Changed Timeline Events
       * @default []
       */
      changed_timeline_events?: components["schemas"]["UserTimelineEvent"][];
      /**
       * Changed Timeline Event States
       * @default []
       */
      changed_timeline_event_states?: components["schemas"]["UserTimelineEventStateChange"][];
      /** @default ONLINE */
      service_status?: components["schemas"]["ServiceStatus"];
    };
    /**
     * NewUserTimelineEventState
     * @description An enumeration.
     * @enum {string}
     */
    NewUserTimelineEventState: "UNVISITED" | "ACTIVE" | "VISITED";
    /**
     * ProgressEventsRequest
     * @description Inputs to use when progressing an audience user along the timeline.
     */
    ProgressEventsRequest: {
      /**
       * Max Steps
       * @description The maximum amount of steps that should be progressed. Use `null` to progress until you meet a blocking condition.
       * @example 1
       */
      max_steps?: number;
      /**
       * Pause At Beats
       * @description Should beat guards be respected when progressing
       * @example true
       */
      pause_at_beats?: boolean;
    };
    /**
     * ServiceStatus
     * @description An enumeration.
     * @enum {string}
     */
    ServiceStatus: "ONLINE" | "MAINTENANCE";
    /**
     * Timeline
     * @description API representation of timeline resource.
     */
    Timeline: {
      /**
       * Id
       * @example 0nfWvgIlDZVk5yndCLKm
       */
      id: string;
      /**
       * Title
       * @example Alice's Adventure In Wonderland
       */
      title: string;
      /**
       * Description
       * @example A 30 day immersive experience in Wonderland.
       */
      description?: string;
    };
    /**
     * TimelineEvent
     * @description
     */
    TimelineEvent: {
      /**
       * Id
       * @example kNSI3QNGVj3OwByy43ze
       */
      id: string;
      /**
       * Title
       * @example Find the flag!
       */
      title: string;
      /**
       * Description
       * @example You have 30 seconds to find the flag - go go go!
       */
      description?: string;
      /**
       * Step
       * @example 1
       */
      step?: number;
      /**
       * Content Integrations
       * @example {
       *   "ACTIVE": [
       *     {
       *       "content_id": {
       *         "example": "MN7S90NBDJ"
       *       },
       *       "content_type": {
       *         "example": "BlogPost"
       *       },
       *       "provider_id": {
       *         "example": "Contentful"
       *       }
       *     }
       *   ]
       * }
       */
      content_integrations: {
        [key: string]: components["schemas"]["ContentIntegration"][];
      };
      /** Narrative Event Id */
      narrative_event_id: string;
      /**
       * Narrative Event Custom Data
       * @default {}
       */
      narrative_event_custom_data?: { [key: string]: string };
    };
    /** TokenIntrospectRequest */
    TokenIntrospectRequest: {
      /**
       * Access Token
       * @description Access Token to introspect
       * @example ryJhbGciOiJSUzI1NiIsImtpZCI6IjQ7OTQ5ZDdkNDA3ZmVjOXIyYWM4ZDYzNWVjYmEwYjdhOTE0LWQ4ZmIiLCJ0eXAiOiJK
       */
      access_token: string;
    };
    /**
     * TokenIntrospectResponse
     * @description Read only representation of the meta data around an access token.
     */
    TokenIntrospectResponse: {
      /**
       * Is Active
       * @description Status of the token.
       */
      is_active: boolean;
      /**
       * User Id
       * @example 4L9MN83KOS
       */
      user_id?: string;
      /**
       * Expires In
       * @description Time in seconds until the access token expires.
       * @example 3600
       */
      expires_in?: number;
    };
    /**
     * TokenRequest
     * @description Request data to generate a new access token for the Audience API.
     */
    TokenRequest: {
      /**
       * User Identifier
       * @description User ID scoped to the Access Token being generated.
       * @example 4L9MN83KOS
       */
      user_id: string;
    };
    /**
     * TokenResponse
     * @description Data returned when an access token is successfully generated.
     */
    TokenResponse: {
      /**
       * Access Token
       * @description Access Token used to authenticate with Audience APIs.
       * @example ryJhbGciOiJSUzI1NiIsImtpZCI6IjQ7OTQ5ZDdkNDA3ZmVjOXIyYWM4ZDYzNWVjYmEwYjdhOTE0LWQ4ZmIiLCJ0eXAiOiJK
       */
      access_token: string;
      /**
       * Expires In
       * @description Time in seconds until the Access Token expires.
       * @example 3600
       */
      expires_in: number;
    };
    /** UpdateVariableValue */
    UpdateVariableValue: {
      /**
       * Value
       * @description New variable value
       * @example 200
       */
      value: string;
    };
    /**
     * User
     * @description API representation of an audience user on a specific timeline.
     */
    User: {
      /**
       * Identifier
       * @description Unique identifier for the user.
       * @example 0HJviYCWMZVYowT7ujWtb7rUEpE3
       */
      id: string;
      /**
       * Variables
       * @description User level variable values
       * @example {
       *   "points": "100",
       *   "deadline": "2023-03-15T10:35:26.336571"
       * }
       */
      variables: { [key: string]: string };
      /**
       * Current Step
       * @description Current step index for user in event delivery sequence
       */
      current_step?: number;
      /**
       * Current Beat
       * @description Current beat based on user narrative progress.
       */
      current_beat?: components["schemas"]["Beat"] | null;
      /**
       * New Beat Available
       * @description Denotes if the next beat is available for progression.
       * @example {
       *   "id": "PYztAWXDPnz4BM6qDzx4",
       *   "name": "Act 1 Beat 4"
       * }
       */
      new_beat_available?: components["schemas"]["Beat"] | null;
      /**
       * Waiting For Condition Id
       * @description Condition currently blocking further progression
       * @example SzamHkfkMHWpaOUqWOy6
       */
      waiting_for_condition_id?: string;
      /**
       * Waiting For Condition Datetime
       * Format: date-time
       * @description If the user is currently blocked due to a time condition, the time at which that condition is expected to pass
       * @example 2023-02-03T09:00:00
       */
      waiting_for_condition_datetime?: string;
      /**
       * End Of Timeline Reached
       * @description Denotes if all progression conditions have been satisfied. Note this does not mean that all delivery conditions (on threads for example) have been satisfied.
       */
      end_of_timeline_reached: boolean;
      /**
       * Datetime Guards Disabled
       * @description Testing feature which skips any time guards if enabled.
       * @example false
       */
      datetime_guards_disabled: boolean;
      /**
       * Pause At Beats
       * @description Should progression execution pause at beats.
       * @example false
       */
      pause_at_beats: boolean;
      /**
       * Active Timeline Id
       * @example nevLb8KWPejFV0t0dy9L
       */
      active_timeline_id: string;
    };
    /**
     * UserResponse
     * @description Base response shape for all single resource Audience API responses.
     */
    UserResponse: {
      data?: components["schemas"]["User"];
      /** Error */
      error?: components["schemas"]["GeneralError"] | null;
      /** Meta */
      meta?: components["schemas"]["Meta"] | null;
    };
    /**
     * UserTimelineEvent
     * @description Represents a user timeline event.
     */
    UserTimelineEvent: {
      /**
       * Id
       * @example kNSI3QNGVj3OwByy43ze
       */
      id: string;
      /** @example ACTIVE */
      state: components["schemas"]["NewUserTimelineEventState"];
      /**
       * Available Step Index
       * @description Identifies the step index in which this event becomes available.
       * @example 1
       */
      available_step_index: number;
      /**
       * Available Beat
       * @description Identifies the beat in which this event becomes available.
       */
      available_beat?: components["schemas"]["Beat"];
      /**
       * Links
       * @description Array of link resources which can be followed to other events.
       */
      links: components["schemas"]["UserTimelineEventLink"][];
      /**
       * Thread Id
       * @example PYztAWXDPnz4BM6qDzx4
       */
      thread_id?: string;
      /**
       * Row Id
       * @example 7D83C0It0Kpm62ZQ1gt9
       */
      row_id: string;
      /**
       * Row Name
       * @example My row title
       */
      row_name: string;
      /**
       * Row Description
       * @example My row description
       */
      row_description?: string;
      /**
       * Previous In Row Timeline Event Id
       * @example IM50smQ3suY3nGOXNjp4
       */
      previous_in_row_timeline_event_id?: string;
      /**
       * Next In Row Timeline Event Id
       * @example s1sad1DkWZephtcJDmtM
       */
      next_in_row_timeline_event_id?: string;
      /**
       * Related Timeline Event Ids
       * @example [
       *   "MN7S90NBDJNSJS"
       * ]
       */
      related_timeline_event_ids: string[];
      /**
       * Narrative Event Id
       * @example 0nfWvgIlDZVk5yndCLKm
       */
      narrative_event_id: string;
      /**
       * Narrative Event Title
       * @example My narrative event
       */
      narrative_event_title?: string;
      /**
       * Narrative Event Description
       * @example My narrative event description
       */
      narrative_event_description?: string;
      /**
       * Narrative Event Content
       * @example [
       *   {
       *     "content_id": "MN7S90NBDJ",
       *     "content_type": "BlogPost",
       *     "provider_id": "Contentful"
       *   },
       *   {
       *     "content_id": "EL4S90NNDL",
       *     "content_type": "BlogPost",
       *     "provider_id": "Contentful"
       *   }
       * ]
       */
      narrative_event_content: components["schemas"]["ContentIntegration"][];
      /**
       * Narrative Event State Changes Content
       * @description State change content associated with this event.
       * @example {
       *   "AVAILABLE": [
       *     {
       *       "content_id": "MN7S90NBDJ",
       *       "content_type": "BlogPost",
       *       "provider_id": "Contentful"
       *     },
       *     {
       *       "content_id": "EL4S90NNDL",
       *       "content_type": "BlogPost",
       *       "provider_id": "Contentful"
       *     }
       *   ],
       *   "VISITED": [
       *     {
       *       "content_id": "MN7S90NBDJ",
       *       "content_type": "BlogPost",
       *       "provider_id": "Contentful"
       *     }
       *   ]
       * }
       */
      narrative_event_state_changes_content: {
        [key: string]: components["schemas"]["ContentIntegration"][];
      };
      /**
       * Narrative Event Custom Data
       * @default {}
       * @example {
       *   "button_text": "Press me"
       * }
       */
      narrative_event_custom_data?: { [key: string]: string };
    };
    /**
     * UserTimelineEventDetailResponse
     * @description Base response shape for all single resource Audience API responses.
     */
    UserTimelineEventDetailResponse: {
      data?: components["schemas"]["UserTimelineEvent"];
      /** Error */
      error?: components["schemas"]["GeneralError"] | null;
      /** Meta */
      meta?: components["schemas"]["Meta"] | null;
    };
    /**
     * UserTimelineEventLink
     * @description Represents a stateful link between two timeline events.
     */
    UserTimelineEventLink: {
      /**
       * Id
       * @example kNSI3QNGVj3OwByy43ze:MN7S90NBDJNSJS
       */
      id: string;
      /**
       * To Event Id
       * @example MN7S90NBDJNSJS
       */
      to_event_id: string;
      /**
       * Label
       * @description Describes the intent of the link
       * @example Accept the mission!
       */
      label?: string;
      /**
       * Followable
       * @description Can the link be followed
       * @example false
       */
      followable: boolean;
      /**
       * Last Followed At
       * Format: date-time
       * @description Timestamp when the link was last followed.
       * @example 2023-02-03T09:01:23
       */
      last_followed_at?: string;
      /**
       * Condition Datetime
       * Format: date-time
       * @description If the link is not followable due to a time condition, the time at which that condition is expected to pass
       * @example 2023-02-03T09:00:00
       */
      condition_datetime?: string;
    };
    /**
     * UserTimelineEventListResponse
     * @description Base response shape for all multiple resource Audience API responses.
     */
    UserTimelineEventListResponse: {
      /** Data */
      data?: components["schemas"]["UserTimelineEvent"][];
      /** Error */
      error?: components["schemas"]["GeneralError"] | null;
      /** Meta */
      meta?: components["schemas"]["Meta"] | null;
    };
    /**
     * UserTimelineEventStateChange
     * @description Represents a user timeline event state change.
     */
    UserTimelineEventStateChange: {
      /** @example ACTIVE */
      state: components["schemas"]["NewUserTimelineEventState"];
      /**
       * State Changed At
       * Format: date-time
       */
      state_changed_at?: string;
      /**
       * State Change Content
       * @example [
       *   {
       *     "content_id": "MN7S90NBDJ",
       *     "content_type": "BlogPost",
       *     "provider_id": "Contentful"
       *   },
       *   {
       *     "content_id": "EL4S90NNDL",
       *     "content_type": "BlogPost",
       *     "provider_id": "Contentful"
       *   }
       * ]
       */
      state_change_content: components["schemas"]["ContentIntegration"][];
      /**
       * Timeline Event Id
       * @example PYztAWXDPnz4BM6qDzx4
       */
      timeline_event_id: string;
      /**
       * Thread Id
       * @example 7D83C0It0Kpm62ZQ1gt9
       */
      thread_id?: string;
      /**
       * Row Id
       * @example i55GFxgI3AODsW9OacUz
       */
      row_id: string;
      /** Row Name */
      row_name: string;
      /**
       * Narrative Event Id
       * @example 0nfWvgIlDZVk5yndCLKm
       */
      narrative_event_id: string;
      /**
       * Narrative Event Title
       * @example My narrative event
       */
      narrative_event_title?: string;
      /**
       * Narrative Event Description
       * @example My narrative event description
       */
      narrative_event_description?: string;
    };
    /**
     * UserTimelineEventStateChangeListResponse
     * @description Base response shape for all multiple resource Audience API responses.
     */
    UserTimelineEventStateChangeListResponse: {
      /** Data */
      data?: components["schemas"]["UserTimelineEventStateChange"][];
      /** Error */
      error?: components["schemas"]["GeneralError"] | null;
      /** Meta */
      meta?: components["schemas"]["Meta"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * Variable
     * @description API representation of a timeline variable.
     */
    Variable: {
      /**
       * Name
       * @example coins
       */
      name: string;
      /** @example shared */
      scope: components["schemas"]["VariableScope"];
      /**
       * Default Value
       * @example 100
       */
      default_value: string;
      /**
       * Value
       * @description Current value of the variable. For user scoped variables this is always None - see an individual user API response for each unique value.
       * @example 200
       */
      value?: string;
    };
    /**
     * VariableScope
     * @description
     *     The scope of a variable.
     *
     *     User values are specific to a single user, shared values are across
     *     all users on a timeline.
     *
     * @enum {string}
     */
    VariableScope: "user" | "shared";
  };
}

export interface operations {
  /** Access Tokens are tied to a specific user, shorted lived (1 hour), and can only be used to authenticate with the Audience API. */
  generate_tokens_auth_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRequest"];
      };
    };
  };
  /**
   * Inspect an access token generated by the authentication API, to view
   * metadata including the expiry datetime.
   */
  token_info_auth_introspect_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenIntrospectResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenIntrospectRequest"];
      };
    };
  };
  /** Access Tokens are tied to a specific user, shorted lived (1 hour), and can only be used to authenticate with the Audience API. */
  generate_tokens_v1_auth_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRequest"];
      };
    };
  };
  /**
   * Inspect an access token generated by the authentication API, to view
   * metadata including the expiry datetime.
   */
  token_info_v1_auth_introspect_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenIntrospectResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenIntrospectRequest"];
      };
    };
  };
  /** Retrieve detailed representation of the current user. */
  get_user_me_users_me_get: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete the user and any user associated objects from the current timeline. */
  delete_user_users_me_delete: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create a new audience user for a Fictioneers powered experience. */
  create_user_users_post: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
  };
  /** Progress along the timeline. */
  step_events_for_user_via_post_users_me_progress_step_post: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Service Unavailable - Potentially due to contention. */
      409: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgressEventsRequest"];
      };
    };
  };
  /** List endpoint for user timeline events. */
  list_user_timeline_events_user_timeline_events_get: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserTimelineEventListResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update the state of the current event to COMPLETED and make the target of the link AVAILABLE (if it has also been reached by step based progression). */
  follow_link_user_timeline_events__user_timeline_event_id__follow_link_post: {
    parameters: {
      path: {
        user_timeline_event_id: string;
      };
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserTimelineEventDetailResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Service Unavailable - Potentially due to contention. */
      409: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FollowLinkRequest"];
      };
    };
  };
  /**
   * List endpoint for user timeline event state changes implicitly filtered by the
   * authenticated user ID.
   */
  get_user_timeline_event_state_changes_user_timeline_event_state_changes_get: {
    parameters: {
      query: {
        content_type?: string;
      };
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserTimelineEventStateChangeListResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Retrieve detailed representation of the current user. */
  get_user_me_v1_users_me_get: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete the user and any user associated objects from the current timeline. */
  delete_user_v1_users_me_delete: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create a new audience user for a Fictioneers powered experience. */
  create_user_v1_users_post: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
  };
  /** Progress along the timeline. */
  step_events_for_user_via_post_v1_users_me_progress_step_post: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Service Unavailable - Potentially due to contention. */
      409: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgressEventsRequest"];
      };
    };
  };
  /** List endpoint for user timeline events. */
  list_user_timeline_events_v1_user_timeline_events_get: {
    parameters: {
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserTimelineEventListResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update the state of the current event to COMPLETED and make the target of the link AVAILABLE (if it has also been reached by step based progression). */
  follow_link_v1_user_timeline_events__user_timeline_event_id__follow_link_post: {
    parameters: {
      path: {
        user_timeline_event_id: string;
      };
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserTimelineEventDetailResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Service Unavailable - Potentially due to contention. */
      409: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FollowLinkRequest"];
      };
    };
  };
  /**
   * List endpoint for user timeline event state changes implicitly filtered by the
   * authenticated user ID.
   */
  get_user_timeline_event_state_changes_v1_user_timeline_event_state_changes_get: {
    parameters: {
      query: {
        content_type?: string;
      };
      header: {
        "fictioneers-user-id"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserTimelineEventStateChangeListResponse"];
        };
      };
      /** Authentication Required */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List all published timelines which users can be placed on. */
  get_timelines_v1_timelines_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Timeline"][];
        };
      };
    };
  };
  /** Representation of a single timeline. */
  get_timeline_v1_timelines__timeline_id__get: {
    parameters: {
      path: {
        timeline_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Timeline"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Lists all variables with their default and current values. */
  list_timeline_variables_v1_timelines__timeline_id__variables_get: {
    parameters: {
      path: {
        timeline_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Variable"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Detail representation of a single timeline variable. */
  detail_timeline_variable_v1_timelines__timeline_id__variables__name__get: {
    parameters: {
      path: {
        timeline_id: string;
        name: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Variable"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update the value of a shared timeline variable. */
  update_timeline_variable_v1_timelines__timeline_id__variables__name__patch: {
    parameters: {
      path: {
        timeline_id: string;
        name: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Variable"];
        };
      };
      /** Service Unavailable - Potentially due to contention. */
      409: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateVariableValue"];
      };
    };
  };
  /** Lists all timeline events on a specific timeline. */
  list_timeline_timeline_events_v1_timelines__timeline_id__timeline_events_get: {
    parameters: {
      path: {
        timeline_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TimelineEvent"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List of all users on timeline. */
  get_timeline_users_v1_timelines__timeline_id__users_get: {
    parameters: {
      path: {
        timeline_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete all users on a timeline. */
  delete_all_timeline_users_v1_timelines__timeline_id__users_delete: {
    parameters: {
      path: {
        timeline_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Retrieves timeline user. */
  get_timeline_user_v1_timelines__timeline_id__users__user_id__get: {
    parameters: {
      path: {
        timeline_id: string;
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete timeline user. */
  delete_timeline_user_v1_timelines__timeline_id__users__user_id__delete: {
    parameters: {
      path: {
        timeline_id: string;
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Returns all event state changes filtered by timeline. */
  list_all_timeline_event_state_changes_v1_timelines__timeline_id__event_state_changes_get: {
    parameters: {
      path: {
        timeline_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EventStateChange"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external {}
